# This workflow should run when:
# - New commit is pushed to master or release branch
name: Build and push image to ECR

on:
  push:
    branches:
      - "master"
      - "release"

jobs:
  build_and_test_job:
    uses: ./.github/workflows/build.yml
    with:
      AWS_REGION: "ap-southeast-1"
    secrets: inherit
